<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrderSeeder extends Seeder
{
    public function run()
    {
        $orders = [
            [
                'user_id' => 1,
                'total_money' => 500000,
                'status' => 'pending',
                'address' => '123 Nguyen Trai, Ha Noi',
                'note' => 'Giao gio hanh chinh',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'total_money' => 1200000,
                'status' => 'shipping',
                'address' => '456 Le Loi, TP HCM',
                'note' => 'Goi truoc khi giao',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            [
                'user_id' => 3,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 4,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 5,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 6,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 7,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 8,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 9,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 10,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 11,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 12,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 13,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 14,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 15,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 16,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 17,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 18,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 19,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 20,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 21,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 22,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 23,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 24,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 25,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'user_id' => 26,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'user_id' => 27,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 28,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 29,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 30,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 31,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 32,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 33,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			[
                'user_id' => 34,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
			
            [
                'user_id' => 35,
                'total_money' => 250000,
                'status' => 'completed',
                'address' => '789 Tran Hung Dao, Da Nang',
                'note' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('orders')->insert($orders);
    }
}